# Generated by Django 3.2 on 2023-04-24 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230424_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usershabit',
            old_name='user_id',
            new_name='user',
        ),
    ]
