# Generated by Django 3.2 on 2023-04-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_id_usershabit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='habits',
            field=models.ManyToManyField(related_name='users', to='users.Habit'),
        ),
        migrations.DeleteModel(
            name='UsersHabit',
        ),
    ]
